import esbuild from 'esbuild';
import process from 'node:process';
import { rmSync } from 'node:fs';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const removeDuplicateMainCss = {
	name: 'remove-duplicate-main-css',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length === 0) {
				rmSync('main.css', { force: true });
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: {
		main: 'src/main.ts',
		styles: 'src/styles.css',
	},
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	// Ketcher's bundle fails to parse in Obsidian when syntax minification is enabled.
	minifyWhitespace: prod,
	minifyIdentifiers: prod,
	outdir: '.',
	plugins: [removeDuplicateMainCss],
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
